/**
 * Host-side access to the bundled offline snapshot. The JSON is a build-time
 * asset (generated by scripts/generate-market-snapshot.mjs, inlined by esbuild
 * into lib/index.js), and the loader re-validates it through the ordinary
 * catalog parser so a stale or hand-edited snapshot degrades exactly like a
 * fetched source — never trusted, only parsed.
 *
 * @module @dsh-app/plugin-market/snapshot
 */

import snapshotAsset from './catalog-snapshot.json'
import { parseCatalogDocument, type CatalogEntry } from './catalog.ts'
import type { SnapshotDocument } from './snapshot-builder.ts'

/** The committed snapshot, projected onto the panel's catalog rows. */
export interface SnapshotFallback {
  readonly entries: readonly CatalogEntry[]
  /** ISO timestamp of the generation run (absent = unusable metadata). */
  readonly snapshotAt?: string
}

/** Last-resort catalog: used only when every source fails and no cache exists. */
export function loadSnapshot(): SnapshotFallback | null {
  const document = snapshotAsset as unknown as SnapshotDocument
  if (typeof document !== 'object' || document === null || !Array.isArray(document.plugins)) return null
  const entries = parseCatalogDocument(document)
  if (entries.length === 0) return null
  const snapshotAt = typeof document.generatedAt === 'string' && document.generatedAt !== ''
    ? document.generatedAt
    : undefined
  return { entries, ...(snapshotAt !== undefined ? { snapshotAt } : {}) }
}
